name: CMake

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: pip install fypp

    - name: Install fiat
      run: |
        git clone https://github.com/ecmwf/ecbuild
        git clone https://github.com/ecmwf-ifs/fiat
        export ecbuild_ROOT=$PWD/ecbuild
        cd fiat
        mkdir build && cd build
        cmake ..  -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/fiat/install
        make
        make install
        ls install/module/ install/lib/

    - name: Build field_api
      run: |
        export fiat_DIR=${{github.workspace}}/fiat/install
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dfiat_HAVE_DOUBLE_PRECISION=ON
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
